// Canonical data for the pipeline: intake buckets and the 15 framework agents.
// Aligned with "The Strategist's Framework Handbook" (Tier 4 Intelligence).

export const STAGES = [
  { num: "01", key: "state", title: "The Save File", role: "Decompose the business into structured state" },
  { num: "02", key: "terrain", title: "Terrain", role: "Read the market and the macro environment" },
  { num: "03", key: "inventory", title: "The Honest Mirror", role: "Score what you actually have" },
  { num: "04", key: "routing", title: "Routing", role: "Choose the growth line" },
  { num: "05", key: "customer", title: "The Customer Layer", role: "Find the jobs, gaps, and build order" },
  { num: "06", key: "wiring", title: "Wiring", role: "Bind strategy to live measures and the org" },
  { num: "07", key: "conductor", title: "The Conductor", role: "Select the one thing that matters now" },
  { num: "08", key: "delegate", title: "Delegation", role: "Route work to humans and agents" },
];

export const INTAKE = [
  { key: "biz", name: "Business description & URL",
    desc: "The starting point: who this company is, in their own words, plus their website. Web-enabled agents research from here.",
    from: "Takes two minutes. Paste the URL and a paragraph.",
    guide: ["Paste the company URL — web-enabled agents will read the site and search from it", "One paragraph on what the company does, from your contact's mouth, not the website", "List their main products/services and rough team size", "Anything unusual worth knowing up front"],
    template: `BUSINESS DESCRIPTION — {company}\n\nWebsite URL: {url}\nIn their own words, what the business does: {paragraph}\nMain products / services: {list}\nTeam size (rough): {n}\nAnything unusual worth knowing: {notes}`,
    readers: ["bmc", "fiveforces", "pestle", "vrio", "blueocean"] },
  { key: "leadership", name: "Leadership interviews",
    desc: "Structured conversations with the exec team — usually your point of contact, ideally the CEO.",
    from: "Run it live in your client interview, or hand them the template to fill and paste back.",
    guide: ["Interview your point of contact — CEO if you can get them", "Ask each question verbatim, capture answers in their words", "If two leaders answer differently, record BOTH — the disagreement is data", "20–30 minutes is enough for a first pass"],
    template: `LEADERSHIP INTERVIEW — {company} — {name, title} — {date}\n\n1. In one paragraph: what does this business do, and for whom?\n2. Who are your 2–3 real customer segments? Which one pays the bills?\n3. Why do customers pick you over the alternative?\n4. How does money actually come in? (streams, rough % each)\n5. What 3 resources/capabilities could you not operate without?\n6. Who are your critical partners/suppliers?\n7. What is the single biggest thing limiting growth right now?\n8. What are the 12-month goals, in priority order?\n9. What is broken internally that everyone knows and nobody fixes?\n10. If a competitor wanted to kill you, what would they attack?`,
    readers: ["bmc"] },
  { key: "crm", name: "CRM / win-loss data",
    desc: "Every deal, its outcome, and the stated reason. Lost deals carry most of the signal.",
    from: "Lightweight now: paste a recent deal list. Live CRM sync later.",
    guide: ["Export or paste the last 20–30 closed deals", "Won AND lost", "The reason column matters more than the amount"],
    template: `DEAL LOG — {company}\n\n[WON/LOST] | {deal} | {approx value} | {reason in one sentence}`,
    readers: ["bmc", "fiveforces", "jtbd"] },
  { key: "ledger", name: "Ledger & financials",
    desc: "Revenue concentration, cost structure, where money actually goes.",
    from: "Summary numbers from the last close. Accounting feed later.",
    guide: ["Rough percentages work", "Top customer and top-5 concentration are the key numbers", "Top 5 cost lines"],
    template: `FINANCIAL SNAPSHOT — {company} — trailing 12 months\n\nRevenue streams and rough %:\nTop customer as % of revenue:\nTop 5 customers as % of revenue:\nTop 5 cost lines:\nGross margin (rough):\nSurprises: {notes}`,
    readers: ["bmc", "fiveforces", "threehorizons", "bsc"] },
  { key: "contracts", name: "Contracts",
    desc: "Terms, switching costs, supplier lock-in — the fine print that sets bargaining power.",
    from: "A summary of key agreements, not the documents.",
    guide: ["Customer side: term, auto-renew, cancellation notice, price-lock", "Supplier side: who is irreplaceable in 90 days?", "Exclusivity or minimums = power data"],
    template: `CONTRACT SUMMARY — {company}\n\nCUSTOMER AGREEMENTS (typical): term | auto-renew | notice | price protection\nSUPPLIERS irreplaceable in 90 days: {list}\nExclusivity / minimums: {list}\nExpiring in 6 months: {list}`,
    readers: ["bmc", "fiveforces"] },
  { key: "tickets", name: "Support tickets",
    desc: "The unfiltered record of where the product fails people.",
    from: "Paste representative tickets or the support lead's top-themes list.",
    guide: ["Top 10 recurring themes with rough counts", "10–20 verbatim tickets", "Note handling: resolved, workaround, ignored"],
    template: `SUPPORT THEMES — {company} — last 90 days\n\n{theme} | rough count | typical wording | current handling\n---\n(paste raw tickets below)`,
    readers: ["jtbd", "vpc", "bsc"] },
  { key: "calls", name: "Call transcripts",
    desc: "Thousands of customer interviews the company ran without noticing.",
    from: "Paste transcripts from their call recorder (Fireflies, Gong, Zoom).",
    guide: ["5–10 transcripts is a real corpus", "Prioritize discovery, lost-deal, and churn calls", "Raw beats summarized"],
    template: `CALL TRANSCRIPTS — {company}\n\n=== CALL: {type} | {date} | {who} ===\n{paste transcript}`,
    readers: ["jtbd", "vpc"] },
  { key: "org", name: "Org chart & roles",
    desc: "Who reports to whom, who owns what, how decisions actually route.",
    from: "Ten minutes with your point of contact.",
    guide: ["Walk the org top-down", "Role, what they actually own, reporting line", "Note where decisions stall"],
    template: `ORG CHART — {company}\n\n{name} | {title} | reports to | actually owns | notes\n\nWhere do decisions stall most: {notes}`,
    readers: ["bmc", "sevens", "raci"] },
  { key: "market", name: "Market & competitor signals",
    desc: "Funding rounds, pricing moves, regulation — the outside world.",
    from: "Their URL, named competitors, and what they know. Research agent later.",
    guide: ["3–5 competitors they actually lose to", "Who do they fear but never see", "Pricing moves, entrants, regulation"],
    template: `MARKET SNAPSHOT — {company}\n\nCompany URL: {url}\nCompetitors we lose to: {list}\nCompetitors we fear: {list}\nRecent market moves: {notes}\n24-month market direction: {notes}`,
    readers: ["fiveforces", "pestle", "vrio", "blueocean"] },
];

export const FW = {
  bmc: { stage: "state", web: true, checklist: true, icon: "▦", name: "Business Model Canvas", role: "The Cartographer", out: "9-box shared state",
    voice: "Before anyone optimizes anything, I draw the map. Nine boxes, one agreed truth. The arguments I start are the valuable part.",
    tools: ["interview_leadership()", "parse_contracts()", "read_ledger()", "reconcile_answers()"],
    docs: ["canvas.state", "reconciliation-log", "disagreement-register"],
    reads: [["All intake sources", "interviews, ledger, contracts, CRM, org chart"], ["Leadership's conflicting answers", "reconciled into one"]],
    insight: "One agreed, machine-readable model of what the business actually is — plus the leadership disagreements surfaced while reconciling it.",
    feeds: ["fiveforces", "pestle", "swot", "vrio", "jtbd", "vpc", "sevens", "bsc"] },
  fiveforces: { stage: "terrain", web: true, icon: "⬠", name: "Porter's Five Forces", role: "The Terrain Scout", out: "5 force scores + dominant pressure",
    voice: "I don't care how good your product is. I care who has the power in this market, and I check five dials to find out. Continuously.",
    tools: ["scan_market_signals()", "compute_concentration()", "parse_win_loss()", "watch_entrants()"],
    docs: ["force-dials.state", "entrant-watchlist", "power-map"],
    reads: [["Customer concentration", "ledger, CRM"], ["Switching costs & terms", "contracts"], ["Win/loss reasons", "CRM"], ["Entrant & substitute signals", "market intel"]],
    insight: "How hard it is to make money here right now, and where the power sits — a live terrain reading, not an annual photograph.",
    feeds: ["swot", "ansoff", "blueocean"] },
  pestle: { stage: "terrain", web: true, icon: "☂", name: "PESTLE", role: "The Weather Station", out: "tagged macro opportunities & threats",
    voice: "Terrain is one thing. I watch the weather above it — regulation, rates, technology curves. The storms nobody inside the building can see forming.",
    tools: ["monitor_regulation()", "track_rates()", "scan_tech_curves()", "tag_exposure()"],
    docs: ["macro-radar.state", "exposure-tags", "horizon-alerts"],
    reads: [["Regulatory & political signals", "market intel"], ["Economic indicators", "rates, spend"], ["Tech & legal shifts", "market intel"]],
    insight: "Which macro systems are moving toward you or away — the forces no internal analysis can see.",
    feeds: ["swot", "threehorizons"] },
  swot: { stage: "inventory", icon: "⊞", name: "SWOT → TOWS", role: "The Option Generator", out: "strategy candidates (SO/ST/WO/WT)",
    voice: "Everyone knows my four quadrants. Almost nobody does the second half — crossing them. That's where the actual strategies fall out.",
    tools: ["gather_quadrants()", "cross_matrix()", "test_against_terrain()", "rank_candidates()"],
    docs: ["quadrants.state", "tows-matrix", "candidate-slate"],
    reads: [["Strengths & weaknesses", "Canvas resources and activities"], ["Opportunities & threats", "Five Forces + PESTLE outputs"]],
    insight: "A generated slate of concrete strategy options — combinations tested against terrain data, not a sticky-note brainstorm.",
    feeds: ["ansoff", "toc"] },
  vrio: { stage: "inventory", web: true, icon: "◈", name: "VRIO", role: "The Moat Inspector", out: "defensible-advantage shortlist",
    voice: "I run your proudest capabilities through four gates, and I have no career to protect. The list that survives is short. It's also the truth.",
    tools: ["inventory_capabilities()", "scan_competitors()", "score_four_gates()", "flag_beliefs()"],
    docs: ["gate-scores.state", "moat-shortlist", "uncomfortable-list"],
    reads: [["Capability inventory", "Canvas key resources & activities"], ["Competitor observables", "market intel"]],
    insight: "What's actually defensible versus what merely feels special — the only honest input to a growth strategy.",
    feeds: ["ansoff", "blueocean", "toc"] },
  ansoff: { stage: "routing", icon: "⊕", name: "Ansoff Matrix", role: "The Route Setter", out: "growth vector + risk profile",
    voice: "Four ways to grow, four very different odds. I do the expected-value math so you place the bet on purpose instead of by drift.",
    tools: ["load_moat_shortlist()", "load_terrain()", "compute_quadrant_ev()", "state_assumptions()"],
    docs: ["growth-vector.state", "risk-profile", "assumption-register"],
    reads: [["Defensible advantages", "VRIO shortlist"], ["Terrain pressure", "Five Forces"], ["Strategy candidates", "TOWS"]],
    insight: "Which growth bet the evidence supports — and what would have to be true for a riskier quadrant to make sense.",
    feeds: ["threehorizons", "toc"] },
  threehorizons: { stage: "routing", icon: "≋", name: "Three Horizons", role: "The Portfolio Warden", out: "time-phased allocation view",
    voice: "I count where the money, people, and attention actually go — H1, H2, H3 — and compare it to what the strategy claims. The gap is usually embarrassing.",
    tools: ["read_allocation()", "classify_initiatives()", "compare_to_strategy()", "flag_starvation()"],
    docs: ["allocation.state", "horizon-map", "starvation-alerts"],
    reads: [["Chosen growth vector", "Ansoff"], ["Macro trajectories", "PESTLE"], ["Actual allocation", "ledger, org data"]],
    insight: "Whether you're starving the future to feed the measurable present — the cash cow with no calves, caught early.",
    feeds: ["bsc", "toc"] },
  blueocean: { stage: "routing", web: true, icon: "≈", name: "Blue Ocean / ERRC", role: "The Map Redrawer", out: "candidate value curves",
    voice: "Everyone else helps you fight for the market that exists. I search for the version of the market where you don't have to fight at all.",
    tools: ["map_factor_space()", "run_errc_search()", "draw_value_curves()", "test_feasibility()"],
    docs: ["factor-space.state", "value-curve-candidates", "errc-grid"],
    reads: [["Competitive factor space", "Five Forces, market intel"], ["Defensible capabilities", "VRIO"]],
    insight: "Alternative maps — ways to redraw the market's boundaries instead of competing inside them.",
    feeds: ["kano", "toc"] },
  jtbd: { stage: "customer", icon: "◎", name: "Jobs To Be Done", role: "The Listener", out: "ranked jobs, pains, gains — with receipts",
    voice: "Your company already ran thousands of customer interviews. They're in the calls, the tickets, the churn notes. Nobody read them. I read all of them.",
    tools: ["ingest_call_corpus()", "mine_tickets()", "extract_jobs()", "weigh_pain_intensity()"],
    docs: ["jobs-ledger.state", "pain-rankings", "receipt-index"],
    reads: [["Sales calls & transcripts", "recorded corpus"], ["Support tickets", "full history"], ["Churn & lost-deal notes", "CRM"]],
    insight: "What progress customers actually hire you for — from the whole corpus, not the eight interviews that confirmed the roadmap.",
    feeds: ["vpc"] },
  vpc: { stage: "customer", icon: "⇄", name: "Value Proposition Canvas", role: "The Fit Mapper", out: "gap list: unmet jobs vs. current offer",
    voice: "I hold what customers hire you for in one hand and what you actually ship in the other. The mismatches glow.",
    tools: ["load_jobs_ledger()", "load_current_offer()", "map_fit()", "extract_gaps()"],
    docs: ["fit-map.state", "gap-list", "orphaned-features"],
    reads: [["Ranked jobs, pains, gains", "JTBD"], ["Current offer", "Canvas value propositions"]],
    insight: "The gaps between what customers hire you for and what you ship — as a list, not an opinion.",
    feeds: ["kano"] },
  kano: { stage: "customer", icon: "✦", name: "Kano Model", role: "The Build Sequencer", out: "prioritized build order",
    voice: "Loud isn't the same as important. I sort must-be from performance from delighter, with evidence attached.",
    tools: ["load_gap_list()", "classify_satisfaction_impact()", "weigh_evidence()", "emit_build_order()"],
    docs: ["kano-classes.state", "build-order", "evidence-weights"],
    reads: [["Gap list", "Value Proposition Canvas"], ["Evidence weights", "JTBD corpus"], ["Value-curve candidates", "Blue Ocean"]],
    insight: "The difference between building what's loud and building what matters — a build order with reasons attached.",
    feeds: ["bsc", "toc"] },
  sevens: { stage: "wiring", icon: "⬡", name: "McKinsey 7S", role: "The Friction Finder", out: "7 alignment gap scores",
    voice: "Correct strategies die quietly all the time. I find where the org will silently vote no — the comp plan, the missing skills, the old routing.",
    tools: ["read_org_chart()", "parse_comp_plans()", "audit_skills()", "score_alignment()"],
    docs: ["alignment-gaps.state", "silent-no-register", "change-load-map"],
    reads: [["The chosen strategy", "routing layer outputs"], ["Structure, systems, staff, skills", "org chart, process docs"]],
    insight: "Where the organization will resist without ever saying so — seven gap scores that explain why the ship isn't turning.",
    feeds: ["toc", "raci"] },
  bsc: { stage: "wiring", icon: "▣", name: "Balanced Scorecard / OKRs", role: "The Memory Keeper", out: "live strategy state — shared memory",
    voice: "I refuse to be a document. Every measure I hold is wired to its source. When a key result stops moving, I say so in week three, not week thirteen.",
    tools: ["bind_measures_to_sources()", "cascade_okrs()", "watch_movement()", "flag_stalls()"],
    docs: ["scorecard.state", "okr-tree", "stall-alerts"],
    reads: [["Objectives & measures", "strategy + Kano build order + Horizons allocation"], ["Live numbers", "ledger, CRM, tickets, pipeline"]],
    insight: "Strategy as state the business writes to — the shared memory every other agent reads.",
    feeds: ["toc"] },
  toc: { stage: "conductor", icon: "◉", name: "Theory of Constraints", role: "The Conductor", out: "THE constraint + ranked interventions",
    voice: "The others hand me a hundred true things. I answer the only question they can't: which one matters right now. Everything else waits. That's not rudeness. That's throughput.",
    tools: ["read_all_findings()", "locate_constraint()", "rank_by_throughput_effect()", "resequence_on_move()"],
    docs: ["constraint.state", "intervention-queue", "resequence-log"],
    reads: [["Every finding upstream", "all agents via shared state"], ["Live throughput data", "Balanced Scorecard"]],
    insight: "Improvement anywhere except the constraint is an illusion. The constraint chooses the roadmap — and when it moves, I re-sequence everything.",
    feeds: ["raci"] },
  raci: { stage: "delegate", icon: "⛬", name: "RACI + Capability Layer", role: "The Dispatcher", out: "routed, governed, attested work",
    voice: "I hand out the work — agents inside enumerated boundaries, humans holding accountability, gates where judgment is required. And I write everything down as I go. The auditor gets an export, not archaeology.",
    tools: ["route_task()", "check_capability_envelope()", "open_approval_gate()", "write_attestation()"],
    docs: ["task-routes.state", "capability-envelopes", "attestation-ledger"],
    reads: [["Ranked interventions", "Theory of Constraints"], ["Org roles & authority", "org chart, 7S"], ["Capability grants", "enumerated scopes"]],
    insight: "Enumerated powers for agents, human authority above machine authority, published standards instead of discretion — evidence as an export.",
    feeds: [] },
};

export const ORDER = ["bmc", "fiveforces", "pestle", "swot", "vrio", "ansoff", "threehorizons", "blueocean", "jtbd", "vpc", "kano", "sevens", "bsc", "toc", "raci"];

export const SOURCES = (() => {
  const s = {}; ORDER.forEach(k => (s[k] = []));
  ORDER.forEach(k => FW[k].feeds.forEach(f => s[f].push(k)));
  return s;
})();
